restaurant_choices = {
  'a': 'American, African',
  'b': 'Barbecue',
  'c': 'Cafe, Cezch, Chinese',
  'd': 'No styles with D in our database!',
  'e': 'No styles with E in our database!',
  'f': 'French',
  'g': 'No styles with G in our database!',
  'h': 'No styles with H in our database!',
  'i': 'Indian, Italian',
  'j': 'Japanese',
  'k': 'No styles with K in our database!',
  'l': 'No styles with L in our database!',
  'm': 'Mexican',
  'n': 'No styles with N in our database!',
  'o': 'No styles with O in our database!',
  'p': 'Pizza',
  'q': 'No styles with Q in our database!',
  'r': 'No styles with R in our database!',
  's': 'No styles with S in our database!',
  't': 'Thai',
  'u': 'No styles with U in our database!',
  'v': 'Vegetarian',
  'w': 'No styles with W in our database!',
  'x': 'No styles with X in our database!',
  'y': 'No styles with Y in our database!',
  'z': 'No styles with Z in our database!'
}